### ISSUE TITLE
Allow to set secrets from file

### ISSUE THREAD

**Issue by skuzzle** [skuzzle/cmp#42]
Docker Swarm secrets can not set environment variables directly. It would be great if there was a way to read the contents for a spring boot property from file. Something like
```yml
services:
  cmpbackend:
    ...
    environment:
    - "spring.security.oauth2.client.registration.google.client-secret=$fromFile(/run/secrets/cmp_google_client_secret)"
```

There is most likely a way in Spring to configure this
