### ISSUE TITLE
RateLimiter IP detection doesn't work

### ISSUE THREAD

**Issue by skuzzle** [skuzzle/cmp#54]
Someone's not setting the X-Forwarded-For header correctly

**Comment by skuzzle** [comment]
Solved by fixing deployment config according to: https://dockerswarm.rocks/traefik/#getting-the-client-ip
> So, the Docker Compose lines:
```
    ports:
      - 80:80
      - 443:443
```
>need to be:
```
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
```
